export const FETCH_SHOPPING_INIT = "FETCH_SHOPPING_INIT";
export const FETCH_SHOPPING_SUCCESS = "FETCH_SHOPPING_SUCCESS";
export const FETCH_SHOPPING_FAILED = "FETCH_SHOPPING_FAILED ";

export const ADD_CART_INIT = "ADD_CART_INIT";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAILED = "ADD_CART_FAILED";

export const MAKE_PAYMENT_INIT = "MAKE_PAYMENT_INIT";
export const MAKE_PAYMENT_SUCCESS = "MAKE_PAYMENT_SUCCESS";
export const MAKE_PAYMENT_FAILED = "MAKE_PAYMENT_FAILED";

// export const WISH_LIST_INIT = "WISH_LIST_INIT";
// export const WISH_LIST_SUCCESS = "WISH_LIST_SUCCESS";
// export const WISH_LIST_FAILED = "WISH_LIST_FAILED";
